# Generated by Django 5.2.5 on 2025-09-03 19:53

import apps.monitoring.db_mixins
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Ensure monitoring schema exists before creating tables
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS monitoring;",
            reverse_sql="DROP SCHEMA IF EXISTS monitoring CASCADE;",
        ),
        migrations.CreateModel(
            name='DeveloperSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='Reference to auth.users.user_id')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('session_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('ide_name', models.CharField(max_length=100)),
                ('ide_version', models.CharField(blank=True, max_length=50, null=True)),
                ('project_path', models.TextField(blank=True, null=True)),
                ('git_repository_url', models.URLField(blank=True, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('git_commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('session_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring.developer_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='monitoring._user_id_6c6aa5_idx'), models.Index(fields=['session_start'], name='monitoring._session_62beee_idx'), models.Index(fields=['created_at'], name='monitoring._created_652f36_idx')],
            },
            bases=(apps.monitoring.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CodeMetrics',
            fields=[
                ('metrics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('file_extension', models.CharField(max_length=20)),
                ('lines_of_code', models.IntegerField(default=0)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_deleted', models.IntegerField(default=0)),
                ('lines_modified', models.IntegerField(default=0)),
                ('complexity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('function_count', models.IntegerField(blank=True, null=True)),
                ('class_count', models.IntegerField(blank=True, null=True)),
                ('comment_lines', models.IntegerField(blank=True, null=True)),
                ('blank_lines', models.IntegerField(blank=True, null=True)),
                ('metrics_metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='code_metrics', to='monitoring.developersession')),
            ],
            options={
                'db_table': 'monitoring.code_metrics',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['session', 'file_path'], name='monitoring._session_318d7a_idx'), models.Index(fields=['file_extension'], name='monitoring._file_ex_3b1222_idx'), models.Index(fields=['calculated_at'], name='monitoring._calcula_41f508_idx'), models.Index(fields=['lines_of_code'], name='monitoring._lines_o_9e5c3d_idx')],
            },
            bases=(apps.monitoring.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('file_open', 'File Open'), ('file_edit', 'File Edit'), ('file_save', 'File Save'), ('file_close', 'File Close'), ('debug_start', 'Debug Start'), ('debug_stop', 'Debug Stop'), ('build_start', 'Build Start'), ('build_complete', 'Build Complete'), ('test_run', 'Test Run'), ('git_commit', 'Git Commit'), ('git_push', 'Git Push'), ('git_pull', 'Git Pull'), ('ide_focus', 'IDE Focus'), ('ide_blur', 'IDE Blur'), ('other', 'Other')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('activity_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='monitoring.developersession')),
            ],
            options={
                'db_table': 'monitoring.activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='monitoring._session_9ad055_idx'), models.Index(fields=['activity_type'], name='monitoring._activit_5f2ac9_idx'), models.Index(fields=['timestamp'], name='monitoring._timesta_a3f3d0_idx'), models.Index(fields=['file_extension'], name='monitoring._file_ex_f69a6e_idx')],
            },
            bases=(apps.monitoring.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GitEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('commit', 'Commit'), ('push', 'Push'), ('pull', 'Pull'), ('fetch', 'Fetch'), ('merge', 'Merge'), ('rebase', 'Rebase'), ('checkout', 'Checkout'), ('branch_create', 'Branch Create'), ('branch_delete', 'Branch Delete'), ('tag_create', 'Tag Create'), ('tag_delete', 'Tag Delete'), ('stash', 'Stash'), ('reset', 'Reset'), ('cherry_pick', 'Cherry Pick')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('commit_message', models.TextField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_name', models.CharField(blank=True, max_length=100, null=True)),
                ('files_changed', models.IntegerField(blank=True, null=True)),
                ('insertions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('git_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='git_events', to='monitoring.developersession')),
            ],
            options={
                'db_table': 'monitoring.git_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='monitoring._session_a8ebca_idx'), models.Index(fields=['event_type'], name='monitoring._event_t_8b106f_idx'), models.Index(fields=['timestamp'], name='monitoring._timesta_1361d9_idx'), models.Index(fields=['commit_hash'], name='monitoring._commit__c01463_idx'), models.Index(fields=['branch_name'], name='monitoring._branch__8079e8_idx')],
            },
            bases=(apps.monitoring.db_mixins.RetryableModelMixin, models.Model),
        ),
    ]
