# Generated by Django 4.2.16 on 2025-09-27 04:54
# Ensure monitoring service works with UUID admin log from auth service

from django.db import migrations, connection


def ensure_admin_log_uuid_compatibility(apps, schema_editor):
    """
    Ensure monitoring service can work with UUID django_admin_log.user_id.
    Since all services share the same database, the admin log must be UUID
    to work with the auth service's UUID User model.
    """
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Check if django_admin_log exists and its user_id type
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'django_admin_log'
            );
        """)
        table_exists = cursor.fetchone()[0]

        if table_exists:
            cursor.execute("""
                SELECT data_type FROM information_schema.columns
                WHERE table_name = 'django_admin_log' AND column_name = 'user_id'
            """)
            current_type = cursor.fetchone()

            if current_type and current_type[0] == 'integer':
                # Convert to UUID to match auth service
                cursor.execute("DELETE FROM django_admin_log;")
                cursor.execute("ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey CASCADE;")
                cursor.execute("ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID;")
                cursor.execute("""
                    ALTER TABLE django_admin_log
                    ADD CONSTRAINT django_admin_log_user_id_fkey
                    FOREIGN KEY (user_id) REFERENCES auth.users(id)
                    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
                """)


def reverse_ensure_admin_log_uuid_compatibility(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_safe_table_rename'),
    ]

    operations = [
        migrations.RunPython(
            ensure_admin_log_uuid_compatibility,
            reverse_ensure_admin_log_uuid_compatibility,
        ),
    ]
