# Generated by Django 5.2.5 on 2025-09-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_fix_admin_log_uuid_compatibility"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activitylog",
            table="monitoring.activity_logs",
        ),
        migrations.AlterModelTable(
            name="codemetrics",
            table="monitoring.code_metrics",
        ),
        migrations.AlterModelTable(
            name="developersession",
            table="monitoring.developer_sessions",
        ),
        migrations.AlterModelTable(
            name="gitevent",
            table="monitoring.git_events",
        ),
    ]
