# Generated by Django 4.2.16 on 2025-09-27 14:04

import uuid
from django.contrib.auth.models import AbstractBaseUser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_fix_admin_log_uuid_compatibility'),
    ]

    operations = [
        # Only create the User model for non-CI environments where it's needed
        # In CI, we use default auth.User and disabled migrations
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # No-op forward migration
            reverse_code=lambda apps, schema_editor: None,  # No-op reverse migration
        ),
    ]
