# Generated by Django 4.2.16 on 2025-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20250927_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('file_open', 'File Open'),
                    ('file_edit', 'File Edit'),
                    ('file_save', 'File Save'),
                    ('file_close', 'File Close'),
                    ('debug_start', 'Debug Start'),
                    ('debug_stop', 'Debug Stop'),
                    ('build_start', 'Build Start'),
                    ('build_complete', 'Build Complete'),
                    ('test_run', 'Test Run'),
                    ('git_commit', 'Git Commit'),
                    ('git_push', 'Git Push'),
                    ('git_pull', 'Git Pull'),
                    ('ide_focus', 'IDE Focus'),
                    ('ide_blur', 'IDE Blur'),
                    ('window_focus', 'Window Focus'),
                    ('other', 'Other'),
                ],
                max_length=50
            ),
        ),
    ]
