# Generated by Django 4.2.16 on 2025-11-22 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20250927_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('file_open', 'File Open'), ('file_edit', 'File Edit'), ('file_save', 'File Save'), ('file_close', 'File Close'), ('debug_start', 'Debug Start'), ('debug_stop', 'Debug Stop'), ('build_start', 'Build Start'), ('build_complete', 'Build Complete'), ('test_run', 'Test Run'), ('git_commit', 'Git Commit'), ('git_push', 'Git Push'), ('git_pull', 'Git Pull'), ('ide_focus', 'IDE Focus'), ('ide_blur', 'IDE Blur'), ('window_focus', 'Window Focus'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='monitoring.activity_logs',
        ),
        migrations.AlterModelTable(
            name='codemetrics',
            table='monitoring.code_metrics',
        ),
        migrations.AlterModelTable(
            name='developersession',
            table='monitoring.developer_sessions',
        ),
        migrations.AlterModelTable(
            name='gitevent',
            table='monitoring.git_events',
        ),
    ]
