# Generated by Django 4.2.16 on 2026-01-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_add_window_focus_activity_type'),
    ]

    operations = [
        # Fix table name collision
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Rename imposter table if it exists and real table exists with wrong name
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'monitoring' AND table_name = 'code_metrics')
                   AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'monitoring' AND table_name = 'monitoring.code_metrics') THEN
                    
                    ALTER TABLE "monitoring"."code_metrics" RENAME TO "code_metrics_legacy";
                    ALTER TABLE "monitoring"."monitoring.code_metrics" RENAME TO "code_metrics";
                    
                -- If only the 'wrong name' table exists (and imposter doesn't), just rename it
                ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'monitoring' AND table_name = 'monitoring.code_metrics') THEN
                    
                    ALTER TABLE "monitoring"."monitoring.code_metrics" RENAME TO "code_metrics";
                    
                END IF;
            END
            $$;
            """,
            reverse_sql=""
        ),
        
        migrations.AddField(
            model_name='codemetrics',
            name='project_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Reference to management.projects.id - optional project association', null=True),
        ),
        
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='activitylog',
                    table='monitoring.activity_logs',
                ),
                migrations.AlterModelTable(
                    name='codemetrics',
                    table='monitoring.code_metrics',
                ),
                migrations.AlterModelTable(
                    name='developersession',
                    table='monitoring.developer_sessions',
                ),
                migrations.AlterModelTable(
                    name='gitevent',
                    table='monitoring.git_events',
                ),
            ]
        ),
    ]
